package com.codepil.platform.domain;

import com.codepil.platform.mongodb.BaseDocument;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * MongoDB document representing a single SDLC run lifecycle.
 *
 * <p>Stored in the {@code agent_runs} collection. One document is created per call to
 * {@code POST /api/v1/runs} and updated throughout the run lifecycle as SSE events arrive
 * from the Python agent-engine.</p>
 *
 * <h3>Status lifecycle</h3>
 * <pre>
 * (created) running → waiting_approval → running → completed
 *                                      → rejected → failed (if max retries exceeded)
 *                                  ↘ failed
 *                                  ↘ escalated (stuck > 30 min)
 * </pre>
 *
 * <p>Inherits {@code id}, {@code createdAt}, {@code updatedAt} from {@link BaseDocument}.
 * Auditing fields are managed automatically by Spring Data MongoDB via {@code @EnableMongoAuditing}
 * in {@link com.codepil.platform.mongodb.MongoConfig}.</p>
 */
@Document(collection = "agent_runs")
public class AgentRun extends BaseDocument {

    /** UUID generated by Java at run creation — stable external identifier. */
    @Indexed(unique = true)
    private String runId;

    /** UUID for LangGraph thread correlation — passed to agent-engine at run start. */
    private String threadId;

    /** Platform product being built (e.g. {@code SelfCare-001}). */
    @Indexed
    private String productId;

    /** Jira epic key that initiated this run (e.g. {@code SC-42}). */
    private String jiraEpicId;

    /**
     * Current run status.
     * Values: {@code running} | {@code waiting_approval} | {@code completed} |
     *         {@code failed} | {@code escalated}
     */
    @Indexed
    private String status;

    /** Name of the active SDLC stage (e.g. {@code requirements}, {@code dev}, {@code qa}). */
    private String currentStage;

    /**
     * Which human gate is currently open.
     * {@code null} when no gate is active; {@code requirements} or {@code staging} when paused.
     */
    private String approvalStage;

    /** Number of QA retry cycles completed so far. Resets to 0 on a new run. */
    private int qaIteration;

    /** Token usage and cost from the agent-engine (keys: input_tokens, output_tokens, cost_usd). */
    private Map<String, Object> llmUsage;

    /** List of error messages from failed stages or tool calls. */
    private List<String> errors;

    /** Okta user ID of the operator who initiated the run. */
    private String initiatedByUserId;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public AgentRun() {
        this.llmUsage = new HashMap<>();
        this.errors = new ArrayList<>();
    }

    // -------------------------------------------------------------------------
    // Getters and Setters — no Lombok; Java records are used for DTOs only
    // -------------------------------------------------------------------------

    public String getRunId() {
        return runId;
    }

    public void setRunId(String runId) {
        this.runId = runId;
    }

    public String getThreadId() {
        return threadId;
    }

    public void setThreadId(String threadId) {
        this.threadId = threadId;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getJiraEpicId() {
        return jiraEpicId;
    }

    public void setJiraEpicId(String jiraEpicId) {
        this.jiraEpicId = jiraEpicId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCurrentStage() {
        return currentStage;
    }

    public void setCurrentStage(String currentStage) {
        this.currentStage = currentStage;
    }

    public String getApprovalStage() {
        return approvalStage;
    }

    public void setApprovalStage(String approvalStage) {
        this.approvalStage = approvalStage;
    }

    public int getQaIteration() {
        return qaIteration;
    }

    public void setQaIteration(int qaIteration) {
        this.qaIteration = qaIteration;
    }

    public Map<String, Object> getLlmUsage() {
        return llmUsage;
    }

    public void setLlmUsage(Map<String, Object> llmUsage) {
        this.llmUsage = llmUsage;
    }

    public List<String> getErrors() {
        return errors;
    }

    public void setErrors(List<String> errors) {
        this.errors = errors;
    }

    public String getInitiatedByUserId() {
        return initiatedByUserId;
    }

    public void setInitiatedByUserId(String initiatedByUserId) {
        this.initiatedByUserId = initiatedByUserId;
    }

    public void addError(String errorMessage) {
        if (this.errors == null) {
            this.errors = new ArrayList<>();
        }
        this.errors.add(errorMessage);
    }
}
