package com.codepil.platform.domain;

import com.codepil.platform.mongodb.BaseDocument;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoDB document representing a human approval gate request.
 *
 * <p>Stored in the {@code approval_requests} collection. One document is created when
 * the agent-engine raises an {@code approval_requested} SSE event. The document moves
 * through the lifecycle {@code pending → approved | rejected}.</p>
 *
 * <h3>Lifecycle</h3>
 * <pre>
 * Agent raises approval_requested event
 *         |
 *         v
 * ApprovalService.createApprovalRequest()  — status = "pending"
 *         |
 *         v  [Slack notification to approver channel]
 *         |
 *         v  [Human reviews in mfe-approval-portal or REST API]
 *         |
 * ApprovalService.processDecision()        — status = "approved" | "rejected"
 *         |
 *         v
 * Agent-engine /api/v1/runs/{runId}/resume is called
 * </pre>
 */
@Document(collection = "approval_requests")
public class ApprovalRequest extends BaseDocument {

    /** FK to {@code agent_runs.runId}. */
    @Indexed
    private String runId;

    /**
     * Which gate checkpoint this approval is for.
     * Values: {@code requirements} | {@code staging}
     */
    private String approvalStage;

    /**
     * Current status of this approval.
     * Values: {@code pending} | {@code approved} | {@code rejected}
     */
    @Indexed
    private String status;

    /** Human-readable summary of what the approver needs to review (generated by the crew). */
    private String artifactSummary;

    /** The decision submitted by the approver — {@code null} until decided. */
    private String decision;

    /** Optional feedback from the approver — required when rejecting. */
    private String feedback;

    /** Okta user ID of the approver who made the decision. */
    private String approvedBy;

    /** Timestamp when the decision was recorded. */
    private Instant decidedAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ApprovalRequest() {}

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getRunId() {
        return runId;
    }

    public void setRunId(String runId) {
        this.runId = runId;
    }

    public String getApprovalStage() {
        return approvalStage;
    }

    public void setApprovalStage(String approvalStage) {
        this.approvalStage = approvalStage;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getArtifactSummary() {
        return artifactSummary;
    }

    public void setArtifactSummary(String artifactSummary) {
        this.artifactSummary = artifactSummary;
    }

    public String getDecision() {
        return decision;
    }

    public void setDecision(String decision) {
        this.decision = decision;
    }

    public String getFeedback() {
        return feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public String getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    public Instant getDecidedAt() {
        return decidedAt;
    }

    public void setDecidedAt(Instant decidedAt) {
        this.decidedAt = decidedAt;
    }
}
